### ISSUE TITLE
请问下你 用mobx 管理react 状态的问题？

### ISSUE THREAD

**Issue by leeyongda** [Jines-z/react-starter-kit#1]
react 路由切换的时候，组件中的数据会清空吗?
比如你在a 页面还没保存数据，在填了一半数据。
你切换到b 页面去浏览，再切换到a 页面。那 a 页面的数据还会在吗 ？

**Comment by itshizhan** [comment]
这个数据肯定要自己处理。
路由切换时如果需要保存数据，前提是切换的时候数据更新到了store中

**Comment by martinwithyou** [comment]
好吧，我想入门mobx，请问这是不是一个好的项目？

**Comment by itshizhan** [comment]
项目不错，学习足够了。不过如果使用到生产项目，还是需要自己完善很多东西的
这里面使用mobx的地方并不多。你可以自己扩展。

**Comment by Jines-z** [comment]
不好意思，刚刚看到，react-router是没有提供类似于vue中的keep-alive那样的功能，保存状态需要手动的，不过mobx可以做到保存状态的，mobx是独立的双向绑定，所以你只需要在组件外new出来并且关联你需要保存的状态就行了，希望能够帮到你
