### ISSUE TITLE
权限优化建议

### ISSUE THREAD

**Issue by StoneCode5** [Jines-z/react-starter-kit#10]
- 现象：
    - 在预览的网页中，在没有登录的情况下，通过直接访问https://beverle-y.github.io/react-starter-kit/#/index 是可以访问到首页的
- 建议：
    - 最好在没有登录的情况，访问https://beverle-y.github.io/react-starter-kit/#/index 应该还是重定向到登录页面

**Comment by Jines-z** [comment]
确实有这个问题，逻辑上不是很完善，感谢指出，抽空我会优化掉。
