### ISSUE TITLE
运行完命令打开报vendor.dll js错误

### ISSUE THREAD

**Issue by singgl** [Jines-z/react-starter-kit#2]
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Refused to execute script from 'http://localhost:8080/dll/vendor.dll.20154.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
store.js:104 Uncaught ReferenceError: vendor_library is not defined
    at Object.dll-reference vendor_library (store.js:104)
    at __webpack_require__ (bootstrap:787)
    at fn (bootstrap:150)
    at Object../node_modules/react/index.js (bootstrap:925)
    at __webpack_require__ (bootstrap:787)
    at fn (bootstrap:150)
    at Module../src/index.js (index.js:1)
    at __webpack_require__ (bootstrap:787)
    at fn (bootstrap:150)
    at Object.0 (store.js:104)

**Comment by Jines-z** [comment]
没遇到过，看起来是dll资源没找到，先 npm run dll，后 start

**Comment by chilam-chen** [comment]
![image](https://user-images.githubusercontent.com/18030335/42978538-ffb0d612-8bff-11e8-9302-872eea6aeca9.png)
![image](https://user-images.githubusercontent.com/18030335/42978531-ee15c3cc-8bff-11e8-8870-7802cca62969.png)
把dll文件改成这样就可以了。

**Comment by chilam-chen** [comment]
![image](https://user-images.githubusercontent.com/18030335/42978555-23a55dfe-8c00-11e8-88d5-38e4851f5009.png)
![image](https://user-images.githubusercontent.com/18030335/42978561-287de756-8c00-11e8-839e-0974cc8799e2.png)
把js文件改成这样就可以了。

**Comment by Jines-z** [comment]
dll的hash改变是因为修改了vendor，如果改变了依赖，run dll 后，是要更改html的。

**Comment by Jines-z** [comment]
现在已经可以动态向html内注入DLL，无需手动修改。
