### ISSUE TITLE
页面F5刷新的时候，左侧menu的状态没有了

### ISSUE THREAD

**Issue by EdisonFan** [Jines-z/react-starter-kit#4]
页面F5刷新的时候，左侧menu的状态没有了

**Comment by Jines-z** [comment]
menu是写死的，第一反应是不可能，也没遇到过，详细说一下怎么没有的？

**Comment by EdisonFan** [comment]
![qq](https://user-images.githubusercontent.com/24697809/43431959-25aacf0c-94a3-11e8-8758-7ed34ecbd93d.jpg)

如图所示，左边二级菜单被隐藏了，菜单状态丢失。

怎么出现的这种情况？操作如下

1、npm start
2、点击左侧-功能管理->功能列表（实际上，点任何二级菜单都可以）
3、F5刷新页面

截图上的情况，便出现了。

**Comment by Jines-z** [comment]
因为我偷懒没想写这个功能，具体的业务逻辑自己加上吧。
在componentWillMount里边判断window.location.pathName，然后设置defaultOpenKeys和defaultSelectedKeys。

**Comment by EdisonFan** [comment]
好的。
