### ISSUE TITLE
启动报错的问题

### ISSUE THREAD

**Issue by zhangqianfeng** [Jines-z/react-starter-kit#5]
楼主，按照你的步骤anzhuang安装完依赖后还是会报错，请帮忙看下是哪里的问题？谢谢
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Refused to execute script from 'http://localhost:8080/dll/vendor.dll.20154.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
 Uncaught ReferenceError: vendor_library is not defined

**Comment by Jines-z** [comment]
[#2](https://github.com/beverle-y/react-starter-kit/issues/2)
