### ISSUE TITLE
一个store 初始化的问题

### ISSUE THREAD

**Issue by 5havv** [Jines-z/react-starter-kit#7]
你好，看了你的代码很受启发，我这里想请教您一个问题

场景：rootStore 中存的个人信息，token 等信息，pageStore 存的页面相关信息

问题：如果按照您的代码里那样初始化代码 ，如果我想在子pageStore 中调用rootStore中的信息，该如何调用？（rootStore 存入 localStorage 是个方案，但是rootStore数据较多的时候可能会很不方便）

**Comment by Jines-z** [comment]
通常，在组件内是可以获取到任意Store的，Store里面的东西，一般来说也是给组件或者说模块来用的。
在组件内@inject('rootStore')后直接用就好了，应该没必要再存一遍。
就像用redux，可以在不同组件内，经过connect后可以获取不同的state，不过一般没人在state内获取其他state。
我隐约记得好像有人问过我相同的问题。。。

**Comment by 5havv** [comment]
好的，多谢多谢
