### ISSUE TITLE
styled-components

### ISSUE THREAD

**Issue by JHX496** [Jines-z/react-starter-kit#8]
你好，我想在项目中使用styled-components，编译时没问题，但/home下显示Sorry, there was a problem loading the page. 代码我添加在main里面，同样的代码在新建的项目中是可以用的代码如下：
import React, { Component } from 'react'
import styled from 'styled-components'

const Input = styled.input`
    font-size: 1.25em;
    padding: 0.5em;
    margin: 0.5em;
    color: palevioletred;
    background: papayawhip;
    border: none;
    border-radius: 3px;

    &:hover {
        box-shadow: inset 1px 1px 2px rgba(0,0,0,0.1);
    }
`

const H1 = styled.h1`
    background-color: #a1a
`

class Home extends Component {
    constructor() {
        super()
    }
    render() {
        return (
            <div className='Home_'>
                home
                <Input placeholder='@mxstbr' type='text' />
                <H1>hi all</H1>
            </div>
        )
    }
}

export default Home

麻烦回复一下，不胜感激

**Comment by JHX496** [comment]
代码被转换成网页了。。。。我再贴一下
“
render() {
        return (
            <div className='Home_'>
                home
                <Input placeholder='@mxstbr' type='text' />
                <H1>hi all</H1>
            </div>
        )
    }
”

**Comment by JHX496** [comment]
。。。
‘<Input placeholder='@mxstbr' type='text' />‘
’<H1>hi all</H1>’

**Comment by JHX496** [comment]
`render() {
        return (
            <div className='Home_'>
                home
                <Input placeholder='@mxstbr' type='text' />
                <H1>hi all</H1>
            </div>
        )
    }`

**Comment by Jines-z** [comment]
hi，出现这个问题，是因为你的styled-components版本太高了。
原因如下：
安装的时候会提示 styled-components@4.1.2" has incorrect peer dependency "react@>= 16.3.0"
运行的时候报错 Object(...) is not a function
因为V4版本中，用了react >16.3中的新context API
var themeContext = createContext();
var themeConsumer = ThemeContext.Consumer;
本项目的react版本为16.2
解决办法：
1、降低styled-components的版本为V3
2、升级react至16.3+

**Comment by JHX496** [comment]
好的，十分感谢，不过我决定采用sass + styled-components 了，https://github.com/wang-qingqing/qing-music 这个项目建的也不错
