### ISSUE TITLE
IE浏览器上白屏，不支持object.assign，用了Object.assign = require('object-assign')无效

### ISSUE THREAD

**Issue by TsangTszKin** [Jines-z/react-starter-kit#9]
IE浏览器上白屏，不支持object.assign，用了Object.assign = require('object-assign')无效

![image](https://user-images.githubusercontent.com/32698113/49994461-85e74800-ffc4-11e8-8e16-66e309711a90.png)
![image](https://user-images.githubusercontent.com/32698113/49994482-93043700-ffc4-11e8-8c8e-7f7f01b494b9.png)

**Comment by Jines-z** [comment]
我试了一下，没能复现你的问题，不过遇到了一些其他问题。例如：Proxy、Symbol、Set等es6函数报错。
然后我改了一下：(这样可以同时解决掉你的问题)
1、mobx降版本到4；
2、引入@babel/polyfill；
3、修改了一点webpack配置。
.babelrc.js
```
"presets": [
    ...
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        ...
      }
    ]
  ]
```
webpack.base.config.js
```
entry: {
        normalize: [path.resolve(srcDir, 'normalize')],
        main: [srcDir]
}
...
```
normalize/index.js
```
require('@babel/polyfill')
```
这样兼容到了ie9，不过ie9不支持css3，动画会失效。
